<VirtualHost *:80>
<?php if ($devMode) : ?>
        SetEnv MAGE_IS_DEVELOPER_MODE 'true'
<?php endif; ?>

        ServerAdmin <?php echo $serverAdmin ?>

        
        DocumentRoot <?php echo $documentRoot ?>

        
        ServerName <?php echo $defaultWebsite->hostName ?>

<?php foreach ($websites as $website) : ?>
<?php if ($website !== $defaultWebsite) : ?>
        ServerAlias <?php echo $website->hostName; ?>

<?php endif; ?>
<?php endforeach; ?>
<?php if (count($websites) > 1) : ?>

# See http://serverfault.com/questions/144091/conditionally-set-an-apache-environment-variable
# for details on conditionally setting an apache environment variable with defaults
<?php foreach ($websites as $website) : ?>
<?php if (!$website->isDefault) : ?>
        SetEnvIfNoCase Host ^<?php echo str_replace('.', '\.', $website->hostName); ?>$ MAGE_RUN_CODE=<?php echo $website->code; ?>

<?php endif; ?>
<?php endforeach; ?>

# Set the defaults:
        SetEnvIf MAGE_RUN_CODE ^$ MAGE_RUN_CODE=<?php echo $defaultWebsite->code; ?>

        SetEnv MAGE_RUN_TYPE 'website'
<?php endif; ?>

        <Directory />
                Options FollowSymLinks
                AllowOverride All
        </Directory>
        <Directory <?php echo $documentRoot ?>>
                Options Indexes FollowSymLinks MultiViews
                AllowOverride All
                Order allow,deny
                allow from all
        </Directory>

        ErrorLog ${APACHE_LOG_DIR}/<?php echo $defaultWebsite->hostName ?>.error.log

        # Possible values include: debug, info, notice, warn, error, crit,
        # alert, emerg.
        LogLevel warn

        CustomLog ${APACHE_LOG_DIR}/<?php echo $defaultWebsite->hostName ?>.access.log combined

</VirtualHost>
