<<?php echo $widgetId ?> type="<?php echo $moduleId ?>/widget_<?php echo $widgetId ?>" module="<?php echo $moduleId ?>">
<name><?php echo $widgetName ?></name>
<?php if ('' != $description) : ?>
    <description><?php echo $description ?></description>
<?php endif; ?>
<?php if (count($widgetParameters) > 0) : ?>
    <parameters>
        <?php foreach ($widgetParameters as $params) : ?>
            <?php if (isset($params['id'])) : ?>
                <<?php echo $params['id'] ?>>
                <?php foreach ($params as $key => $value) : ?>
                    <?php if ($key == 'id') : continue; endif; ?>
                    <<?php echo $key ?>><?php echo $value ?></<?php echo $key ?>>
                <?php endforeach; ?>
                </<?php echo $params['id'] ?>>
            <?php endif; ?>
    <?php endforeach; ?>
    </parameters>
<?php endif; ?>
</<?php echo $widgetId ?>>
